#ifndef SPRITE_DATA_HPP
#define SPRITE_DATA_HPP

enum SpriteId {
    SPRITE_ID_GEOM,
    SPRITE_ID_TEX1,
    SPRITE_ID_TEX2,
    SPRITE_ID_TEX3,
    SPRITE_ID_TEX4,

    SPRITE_ID_WIDGET_BG_DEBUG,
    SPRITE_ID_CIRCLE,

    SPRITE_ID_COUNT
};

#endif // SPRITE_DATA_HPP
